#!/bin/bash

# Set up access to the system clipboard from within tmux when possible
# Credit: https://gist.github.com/elasticdog/1462391

if [[ ( $OSTYPE == darwin* ) && ( -x $(which reattach-to-user-namespace 2>/dev/null) ) ]]; then
     # on OS X force tmux's default command to spawn a shell in the user's namespace
     # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
     tweaked_config=$(cat $HOME/.tmux.conf <(echo 'set-option -g default-command "reattach-to-user-namespace -l $SHELL"'))

     tmux -f <(echo "$tweaked_config") "$@"
else
     tmux "$@"
fi
